With the assistance of chatgpt4-o

---

之前已經知道：
1. 專有名詞的對齊，需要：
  * 原本的句子：包含，
    * text
    * 切過後的結果
  * 翻譯後的句子：包含，
    * text
    * 切過後的結果
  * 詞對齊的對照。
2. 例如：
  * 原本的句子
    * "張三先生去了北京"
    * ['張三', '先生', '去', '了', '北京']
  * 翻譯後的句子
    * "Mr. Zhang San went to Beijing"
    *  ["Mr.", "Zhang San", "went", "to", "Beijing"]
  * 詞對齊的對照
    * {0: 0, 1: 1, 2: 3, 3: 4}
3. 透過以上的資訊，可以修正翻譯為：
  * ['Mr.', '張三', 'went', 'to', '北京']

## 相關套件的 survey

### [HanLP](https://github.com/hankcs/HanLP)

In [ ]:
!pip install hanlp[full]

Collecting hanlp[full]
  Downloading hanlp-2.1.0b61-py3-none-any.whl.metadata (13 kB)
Collecting hanlp-common>=0.0.20 (from hanlp[full])
  Downloading hanlp_common-0.0.20.tar.gz (28 kB)
  Preparing metadata (setup.py) ... done
Collecting hanlp-downloader (from hanlp[full])
  Downloading hanlp_downloader-0.0.25.tar.gz (13 kB)
  Preparing metadata (setup.py) ... done
Collecting hanlp-trie>=0.0.4 (from hanlp[full])
  Downloading hanlp_trie-0.0.5.tar.gz (6.7 kB)
  Preparing metadata (setup.py) ... done
Collecting pynvml (from hanlp[full])
  Downloading pynvml-11.5.3-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: sentencepiece>=0.1.91 in /usr/local/lib/python3.10/dist-packages (from hanlp[full]) (0.1.99)
Requirement already satisfied: termcolor in /usr/local/lib/python3.10/dist-packages (from hanlp[full]) (2.4.0)
Collecting toposort==1.5 (from hanlp[full])
  Downloading toposort-1.5-py2.py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from hanlp[full]) (2.4.0+cu121)
Requirement already satisfied: transformers>=4.1.1 in /usr/local/lib/python3.10/dist-packages (from hanlp[full]) (4.44.2)
Collecting fasttext-wheel==0.9.2 (from hanlp[full])
  Downloading fasttext_wheel-0.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (16 kB)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.10/dist-packages (from hanlp[full]) (3.3)
Collecting penman==1.2.1 (from hanlp[full])
  Downloading Penman-1.2.1-py3-none-any.whl.metadata (7.8 kB)
Collecting perin-parser>=0.0.12 (from hanlp[full])
  Downloading perin_parser-0.0.14.tar.gz (232 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.4/232.4 kB 5.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting tensorflow<2.14,>=2.6.0 (from hanlp[full])
  Downloading tensorflow-2.13.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Collecting pybind11>=2.2 (from fasttext-wheel==0.9.2->hanlp[full])
  Downloading pybind11-2.13.5-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: setuptools>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from fasttext-wheel==0.9.2->hanlp[full]) (71.0.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from fasttext-wheel==0.9.2->hanlp[full]) (1.26.4)
Collecting phrasetree>=0.0.9 (from hanlp-common>=0.0.20->hanlp[full])
  Downloading phrasetree-0.0.9.tar.gz (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 1.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from perin-parser>=0.0.12->hanlp[full]) (1.13.1)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.14,>=2.6.0->hanlp[full]) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.14,>=2.6.0->hanlp[full]) (1.6.3)
Requirement already satisfied: flatbuffers>=23.1.21 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.14,>=2.6.0->hanlp[full]) (24.3.25)
Collecting gast<=0.4.0,>=0.2.1 (from tensorflow<2.14,>=2.6.0->hanlp[full])
  Downloading gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.14,>=2.6.0->hanlp[full]) (0.2.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.14,>=2.6.0->hanlp[full]) (1.64.1)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.14,>=2.6.0->hanlp[full]) (3.11.0)
Collecting keras<2.14,>=2.13.1 (from tensorflow<2.14,>=2.6.0->hanlp[full])
  Downloading keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.14,>=2.6.0->hanlp[full]) (18.1.1)
Collecting numpy (from fasttext-wheel==0.9.2->hanlp[full])
  Downloading numpy-1.24.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.14,>=2.6.0->hanlp[full]) (3.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.14,>=2.6.0->hanlp[full]) (24.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.14,>=2.6.0->hanlp[full]) (3.20.3)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.14,>=2.6.0->hanlp[full]) (1.16.0)
Collecting tensorboard<2.14,>=2.13 (from tensorflow<2.14,>=2.6.0->hanlp[full])
  Downloading tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow<2.14,>=2.6.0->hanlp[full])
  Downloading tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow<2.14,>=2.6.0->hanlp[full])
  Downloading typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.14,>=2.6.0->hanlp[full]) (1.16.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.14,>=2.6.0->hanlp[full]) (0.37.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->hanlp[full]) (3.15.4)
INFO: pip is looking at multiple versions of torch to determine which version is compatible with other requirements. This could take a while.
Collecting torch>=1.6.0 (from hanlp[full])
  Downloading torch-2.4.1-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
  Downloading torch-2.4.0-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
  Downloading torch-2.3.1-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
  Downloading torch-2.3.0-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
  Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
  Downloading torch-2.2.1-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
  Downloading torch-2.2.0-cp310-cp310-manylinux1_x86_64.whl.metadata (25 kB)
INFO: pip is still looking at multiple versions of torch to determine which version is compatible with other requirements. This could take a while.
  Downloading torch-2.1.2-cp310-cp310-manylinux1_x86_64.whl.metadata (25 kB)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->hanlp[full]) (1.13.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->hanlp[full]) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->hanlp[full]) (2024.6.1)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch>=1.6.0->hanlp[full])
  Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch>=1.6.0->hanlp[full])
  Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch>=1.6.0->hanlp[full])
  Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch>=1.6.0->hanlp[full])
  Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch>=1.6.0->hanlp[full])
  Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch>=1.6.0->hanlp[full])
  Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch>=1.6.0->hanlp[full])
  Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch>=1.6.0->hanlp[full])
  Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch>=1.6.0->hanlp[full])
  Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.18.1 (from torch>=1.6.0->hanlp[full])
  Downloading nvidia_nccl_cu12-2.18.1-py3-none-manylinux1_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch>=1.6.0->hanlp[full])
  Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==2.1.0 (from torch>=1.6.0->hanlp[full])
  Downloading triton-2.1.0-0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.3 kB)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.6.0->hanlp[full])
  Downloading nvidia_nvjitlink_cu12-12.6.68-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.1.1->hanlp[full]) (0.24.6)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.1.1->hanlp[full]) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.1.1->hanlp[full]) (2024.5.15)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers>=4.1.1->hanlp[full]) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.1.1->hanlp[full]) (0.4.4)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.1.1->hanlp[full]) (0.19.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.1.1->hanlp[full]) (4.66.5)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow<2.14,>=2.6.0->hanlp[full]) (0.44.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.14,>=2.13->tensorflow<2.14,>=2.6.0->hanlp[full]) (2.27.0)
Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow<2.14,>=2.6.0->hanlp[full])
  Downloading google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.14,>=2.13->tensorflow<2.14,>=2.6.0->hanlp[full]) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.14,>=2.13->tensorflow<2.14,>=2.6.0->hanlp[full]) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.14,>=2.13->tensorflow<2.14,>=2.6.0->hanlp[full]) (3.0.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers>=4.1.1->hanlp[full]) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers>=4.1.1->hanlp[full]) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers>=4.1.1->hanlp[full]) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers>=4.1.1->hanlp[full]) (2024.8.30)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.6.0->hanlp[full]) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.6.0->hanlp[full]) (1.3.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow<2.14,>=2.6.0->hanlp[full]) (5.5.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow<2.14,>=2.6.0->hanlp[full]) (0.4.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow<2.14,>=2.6.0->hanlp[full]) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow<2.14,>=2.6.0->hanlp[full]) (1.3.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow<2.14,>=2.6.0->hanlp[full]) (0.6.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow<2.14,>=2.6.0->hanlp[full]) (3.2.2)
Downloading fasttext_wheel-0.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 40.6 MB/s eta 0:00:00
Downloading Penman-1.2.1-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 2.0 MB/s eta 0:00:00
Downloading toposort-1.5-py2.py3-none-any.whl (7.6 kB)
Downloading tensorflow-2.13.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (479.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 479.7/479.7 MB 2.4 MB/s eta 0:00:00
Downloading torch-2.1.2-cp310-cp310-manylinux1_x86_64.whl (670.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.2/670.2 MB 1.9 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 3.6 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 53.4 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 21.3 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 30.2 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.4 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 8.2 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 11.4 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 7.2 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 5.9 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.18.1-py3-none-manylinux1_x86_64.whl (209.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.8/209.8 MB 6.0 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 7.3 MB/s eta 0:00:00
Downloading triton-2.1.0-0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.2/89.2 MB 8.1 MB/s eta 0:00:00
Downloading hanlp-2.1.0b61-py3-none-any.whl (651 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 651.6/651.6 kB 34.1 MB/s eta 0:00:00
Downloading pynvml-11.5.3-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 3.5 MB/s eta 0:00:00
Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Downloading keras-2.13.1-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 57.3 MB/s eta 0:00:00
Downloading numpy-1.24.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 65.3 MB/s eta 0:00:00
Downloading pybind11-2.13.5-py3-none-any.whl (240 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 241.0/241.0 kB 15.0 MB/s eta 0:00:00
Downloading tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 74.6 MB/s eta 0:00:00
Downloading tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.8/440.8 kB 26.1 MB/s eta 0:00:00
Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Downloading google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
Downloading nvidia_nvjitlink_cu12-12.6.68-py3-none-manylinux2014_x86_64.whl (19.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 63.2 MB/s eta 0:00:00
Building wheels for collected packages: hanlp-common, hanlp-trie, perin-parser, hanlp-downloader, phrasetree
  Building wheel for hanlp-common (setup.py) ... done
  Created wheel for hanlp-common: filename=hanlp_common-0.0.20-py3-none-any.whl size=30633 sha256=b1c23fe69c54e12753ab13b3322e8ea3cc13da51a782dce0d6a62e83a4bdbb70
  Stored in directory: /root/.cache/pip/wheels/06/2c/84/7bdb23dafe011f728e07335a5e7687c6ad45576115964b21a6
  Building wheel for hanlp-trie (setup.py) ... done
  Created wheel for hanlp-trie: filename=hanlp_trie-0.0.5-py3-none-any.whl size=6817 sha256=f60df5756acad1bf2527411a24ff1f51c7733556689cacb3b180780e5eedd9f1
  Stored in directory: /root/.cache/pip/wheels/4b/ff/a9/6883d860cbed0247ce316c39757ff61c1f5bfd3556abfbefa0
  Building wheel for perin-parser (setup.py) ... done
  Created wheel for perin-parser: filename=perin_parser-0.0.14-py3-none-any.whl size=316649 sha256=685bf76434e1c2dcf20e08253d7044b524677bf2df722b4ec60a745ff1671fb3
  Stored in directory: /root/.cache/pip/wheels/72/f8/35/186cc5a4914d856f2f5086d95be18c3b569dbc7a1f674e42b2
  Building wheel for hanlp-downloader (setup.py) ... done
  Created wheel for hanlp-downloader: filename=hanlp_downloader-0.0.25-py3-none-any.whl size=13747 sha256=4945517e8baa5111e7ff62ce9036956984cfe5768dc93da023baa84d902e8d2b
  Stored in directory: /root/.cache/pip/wheels/71/2b/67/65892ee65ea68b4c0936b9a8f2ea73665c3389fec08746b949
  Building wheel for phrasetree (setup.py) ... done
  Created wheel for phrasetree: filename=phrasetree-0.0.9-py3-none-any.whl size=44218 sha256=121a760659f3fa7a0dfaaf6c32cc64189127323e7ef774f438c426f5ec226996
  Stored in directory: /root/.cache/pip/wheels/61/df/09/e14b1cc4c92a1ed7e1d52647fde6f3e1169ea9cf2df78f1936
Successfully built hanlp-common hanlp-trie perin-parser hanlp-downloader phrasetree
Installing collected packages: toposort, phrasetree, penman, typing-extensions, triton, tensorflow-estimator, pynvml, pybind11, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, keras, hanlp-common, gast, nvidia-cusparse-cu12, nvidia-cudnn-cu12, hanlp-trie, hanlp-downloader, fasttext-wheel, perin-parser, nvidia-cusolver-cu12, google-auth-oauthlib, torch, tensorboard, tensorflow, hanlp
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.12.2
    Uninstalling typing_extensions-4.12.2:
      Successfully uninstalled typing_extensions-4.12.2
  Attempting uninstall: nvidia-nccl-cu12

In [ ]:
import hanlp
HanLP = hanlp.load(hanlp.pretrained.mtl.CLOSE_TOK_POS_NER_SRL_DEP_SDP_CON_ELECTRA_SMALL_ZH)

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

In [ ]:
HanLP(['張三在台北101前面拍了很多照片。'])

{'tok/fine': [['張三', '在', '台北', '101', '前面', '拍', '了', '很多', '照片', '。']],
 'tok/coarse': [['張三', '在', '台北', '101', '前面', '拍', '了', '很多', '照片', '。']],
 'pos/ctb': [['NR', 'P', 'NR', 'CD', 'NN', 'VV', 'AS', 'CD', 'NN', 'PU']],
 'pos/pku': [['nr', 'p', 'ns', 'm', 'f', 'v', 'u', 'm', 'n', 'w']],
 'pos/863': [['nh', 'p', 'ns', 'm', 'nd', 'v', 'u', 'a', 'n', 'w']],
 'ner/msra': [[('張三', 'PERSON', 0, 1),
   ('台北', 'LOCATION', 2, 3),
   ('101', 'DECIMAL', 3, 4)]],
 'ner/pku': [[('張三', 'nr', 0, 1), ('台北', 'ns', 2, 3)]],
 'ner/ontonotes': [[('張三', 'PERSON', 0, 1), ('台北101', 'FAC', 2, 4)]],
 'srl': [[[('張三', 'ARG0', 0, 1),
    ('在台北101前面', 'ARGM-LOC', 1, 5),
    ('拍', 'PRED', 5, 6),
    ('很多照片', 'ARG1', 7, 9)]]],
 'dep': [[(6, 'nsubj'),
   (6, 'prep'),
   (4, 'dep'),
   (5, 'lobj'),
   (2, 'pobj'),
   (0, 'root'),
   (6, 'asp'),
   (9, 'nummod'),
   (6, 'dobj'),
   (6, 'punct')]],
 'sdp': [[[(6, 'Agt')],
   [(4, 'mPrep')],
   [(4, 'Nmod')],
   [(6, 'Datv')],
   [(4, 'mRang')],
   [(0, 'Root')],
   [(6, 'mTime')],
   [(9, 'Quan')],
   [(6, 'Prod')],
   [(6, 'mPunc')]]],
 'con': [['TOP', [['IP', [['NP', [['NR', ['張三']]]], ['VP', [['PP', [['P', ['在']], ['NP', [['QP', [['NP', [['NR', ['台北']]]], ['QP', [['CD', ['101']]]]]], ['NP', [['NN', ['前面']]]]]]]], ['VP', [['VV', ['拍']], ['AS', ['了']], ['NP', [['QP', [['CD', ['很多']]]], ['NP', [['NN', ['照片']]]]]]]]]], ['PU', ['。']]]]]]]}

在使用 HanLP 進行命名實體識別（NER）時，像 `ner/msra`、`ner/pku`、`ner/ontonotes` 這些模型會返回一個三元組（entity, label, start, end）。其中，**後面的數字**是代表實體在句子中的**位置**，具體來說：

- **start**: 實體的**開始位置**（包含該索引）。
- **end**: 實體的**結束位置**（不包含該索引，Python 中範圍通常是左閉右開）。

例如：

```python
'ner/msra': [[('張三', 'PERSON', 0, 1), ('台北', 'LOCATION', 2, 3), ('101', 'DECIMAL', 3, 4)]]
```

- `'張三'` 是一個命名實體，類型是 `PERSON`，出現在句子中從位置 `0` 開始，位置 `1` 結束（所以實際上只包含第 `0` 個字，也就是「張三」）。
- `'台北'` 是一個地名（`LOCATION`），從位置 `2` 開始，到 `3` 結束（只包含「台北」這個詞）。
- `'101'` 是一個數字（`DECIMAL`），從位置 `3` 開始，到 `4` 結束（只包含「101」這個數字）。

同理，`ner/pku` 和 `ner/ontonotes` 也依此原則返回命名實體及其在句子中的位置範圍。

----

句子是切完後的句子（`[['張三', '在', '台北', '101', '前面', '拍', '了', '很多', '照片', '。']]`）這種數據的索引

In [ ]:
test = HanLP(['張三在台北101前面拍了很多照片。'])
print(test['tok/fine'])
print(test['tok/coarse'])
print(test['ner/ontonotes'])

[['張三', '在', '台北', '101', '前面', '拍', '了', '很多', '照片', '。']]
[['張三', '在', '台北', '101', '前面', '拍', '了', '很多', '照片', '。']]
[[('張三', 'PERSON', 0, 1), ('台北101', 'FAC', 2, 4)]]

In [ ]:
ontonotes_nounlist = [ item[0] for item in test['ner/ontonotes'][0]]
pku_nounlist = [ item[0] for item in test['ner/pku'][0]]
msra_nounlist = [ item[0] for item in test['ner/msra'][0]]

print(ontonotes_nounlist)
print(pku_nounlist)
print(msra_nounlist)

['張三', '台北101']
['張三', '台北']
['張三', '台北', '101']

In [ ]:
print(tuple(ontonotes_nounlist))
print(tuple(pku_nounlist))
print(tuple(msra_nounlist))

('張三', '台北101')
('張三', '台北')
('張三', '台北', '101')

### [spaCy](https://github.com/explosion/spaCy)

中文套件可參考[這個](https://spacy.io/models/zh)

[套件區別](https://chatgpt.com/share/74bcb851-2e76-4f8d-9e7b-3f1009087045)

In [ ]:
!pip install -qU pip setuptools wheel
!pip install -qU spacy
!python -m spacy download zh_core_web_sm
!python -m spacy download zh_core_web_md
!python -m spacy download zh_core_web_lg
!python -m spacy download zh_core_web_trf

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
tf-keras 2.17.0 requires tensorflow<2.18,>=2.17, but you have tensorflow 2.13.1 which is incompatible.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 1.4.14 requires numpy>=1.24.4, but you have numpy 1.24.3 which is incompatible.
tensorflow 2.13.1 requires typing-extensions<4.6.0,>=3.6.6, but you have typing-extensions 4.12.2 which is incompatible.
tf-keras 2.17.0 requires tensorflow<2.18,>=2.17, but you have tensorflow 2.13.1 which is incompatible.
torchaudio 2.4.0+cu121 requires torch==2.4.0, but you have torch 2.1.2 which is incompatible.
torchvision 0.19.0+cu121 requires torch==2.4.0, but you have torch 2.1.2 which is incompatible.
Collecting zh-core-web-sm==3.7.0
  Downloading https://github.com/explosion/spacy-models/releases/download/zh_core_web_sm-3.7.0/zh_core_web_sm-3.7.0-py3-none-any.whl (48.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 MB 42.7 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.8.0,>=3.7.0 in /usr/local/lib/python3.10/dist-packages (from zh-core-web-sm==3.7.0) (3.7.6)
Collecting spacy-pkuseg<0.1.0,>=0.0.27 (from zh-core-web-sm==3.7.0)
  Downloading spacy_pkuseg-0.0.33-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (0.12.5)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (4.66.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2.8.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (3.1.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (74.1.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (24.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (3.4.0)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (1.24.3)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.10/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (1.2.0)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2024.8.30)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (13.8.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (0.19.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (7.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2.1.5)
Requirement already satisfied: marisa-trie>=0.7.7 in /usr/local/lib/python3.10/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (1.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2.16.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.10/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (1.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (0.1.2)
Downloading spacy_pkuseg-0.0.33-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 36.7 MB/s eta 0:00:00
Installing collected packages: spacy-pkuseg, zh-core-web-sm
Successfully installed spacy-pkuseg-0.0.33 zh-core-web-sm-3.7.0
✔ Download and installation successful
You can now load the package via spacy.load('zh_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
Collecting zh-core-web-md==3.7.0
  Downloading https://github.com/explosion/spacy-models/releases/download/zh_core_web_md-3.7.0/zh_core_web_md-3.7.0-py3-none-any.whl (78.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.0/78.0 MB 42.1 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.8.0,>=3.7.0 in /usr/local/lib/python3.10/dist-packages (from zh-core-web-md==3.7.0) (3.7.6)
Requirement already satisfied: spacy-pkuseg<0.1.0,>=0.0.27 in /usr/local/lib/python3.10/dist-packages (from zh-core-web-md==3.7.0) (0.0.33)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (0.12.5)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (4.66.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2.8.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (3.1.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (74.1.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (24.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (3.4.0)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (1.24.3)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.10/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (1.2.0)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2024.8.30)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (13.8.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (0.19.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (7.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2.1.5)
Requirement already satisfied: marisa-trie>=0.7.7 in /usr/local/lib/python3.10/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (1.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2.16.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.10/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (1.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (0.1.2)
Installing collected packages: zh-core-web-md
Successfully installed zh-core-web-md-3.7.0
✔ Download and installation successful
You can now load the package via spacy.load('zh_core_web_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
Collecting zh-core-web-lg==3.7.0
  Downloading https://github.com/explosion/spacy-models/releases/download/zh_core_web_lg-3.7.0/zh_core_web_lg-3.7.0-py3-none-any.whl (603.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 603.0/603.0 MB 25.3 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.8.0,>=3.7.0 in /usr/local/lib/python3.10/dist-packages (from zh-core-web-lg==3.7.0) (3.7.6)
Requirement already satisfied: spacy-pkuseg<0.1.0,>=0.0.27 in /usr/local/lib/python3.10/dist-packages (from zh-core-web-lg==3.7.0) (0.0.33)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (0.12.5)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (4.66.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (2.8.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (3.1.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (74.1.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (24.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (3.4.0)

In [ ]:
import spacy
nlp = spacy.load("zh_core_web_trf")
nlp('張三在台北101前面拍了很多照片。')

張三在台北101前面拍了很多照片。

In [ ]:
doc = nlp('張三在台北101前面拍了很多照片。')
doc.ents

(張三, 台北101)

In [ ]:
tok = list(list(token.text for token in doc))
print(tok)

['張三', '在', '台北', '101', '前面', '拍', '了', '很多', '照片', '。']

In [ ]:
ent = list(list(str(ent) for ent in doc.ents))
print(ent)

['張三', '台北101']

# 30 個繁體中文句子

* Generated by Chatgpt-4o.
* Ref with [a messy dialogue](https://chatgpt.com/share/d5b671c8-432d-4465-a8bc-5255c73b3ee6).

In [ ]:
test_sentence = {
  "sentences": [
    "張三在台北101前面拍了很多照片。",
    "李四昨天在台中火車站迷路了。",
    "王五參加了鴻海公司的年度大會。",
    "華為手機在全球市場上的銷量持續增長。",
    "張三開了一間叫做「香格里拉」的餐廳。",
    "小明帶著他的iPhone去了華山藝文中心。",
    "你知道Apple的總部在哪裡嗎？",
    "昨天在星巴克遇見了老朋友林小明。",
    "上海是中國的經濟中心。",
    "Google正在開發一個新的AI模型。",
    "馬雲創辦的阿里巴巴是中國最大的電商平台之一。",
    "珠穆朗瑪峰是世界最高的山。",
    "高雄的六合夜市是美食愛好者的天堂。",
    "臺灣大學的學生來參加這次比賽。",
    "蘋果電腦的發明改變了整個科技產業。",
    "中國移動的用戶數量每年都在增加。",
    "香港的金融市場非常活躍。",
    "IBM推出了一款全新的量子計算機。",
    "Microsoft的Windows系統是全球最常用的操作系統之一。",
    "劉德華出演了很多經典的電影。",
    "台灣的玉山是當地最高的山峰。",
    "世界衛生組織在日內瓦總部召開會議。",
    "任天堂的Switch遊戲機在全球大受歡迎。",
    "中央電視台播放了關於新冠疫情的最新報導。",
    "奧林匹克運動會將在東京舉行。",
    "特斯拉的自動駕駛技術引發了廣泛關注。",
    "小紅書是一個非常受歡迎的社交平台。",
    "Facebook的隱私政策再次引發爭議。",
    "日本的富士山每年都吸引大量遊客。",
    "李小龍的武術精神影響了全世界。"
  ]
}

### [HanLP](https://github.com/hankcs/HanLP)

In [ ]:
res_dataframe = {}
src_sent = []
fin_res = []
coars_res = []
onto_res = []
pku_res = []
msra_res = []

for source_sentence in test_sentence["sentences"]:
  src_sent.append(source_sentence)

  doc = HanLP(source_sentence)
  fin = doc['tok/fine']
  coarse = doc['tok/coarse']

  fin_res.append(fin)
  coars_res.append(coarse)

  ontonotes_nounlist = tuple([item[0] for item in doc['ner/ontonotes']])
  pku_nounlist = tuple([item[0] for item in doc['ner/pku']])
  msra_nounlist = tuple([ item[0] for item in doc['ner/msra']])

  onto_res.append(ontonotes_nounlist)
  pku_res.append(pku_nounlist)
  msra_res.append(msra_nounlist)

In [ ]:
import pandas as pd

df = pd.DataFrame(list(zip(src_sent, fin_res, coars_res, onto_res, pku_res, msra_res)),
               columns =['原句', 'fine', 'coarse', 'ner_onto', 'ner_pku' , 'ner_msra'])

In [ ]:
df.head(30)

,原句,fine,coarse,ner_onto,ner_pku,ner_msra
0,張三在台北101前面拍了很多照片。,"[張三, 在, 台北, 101, 前面, 拍, 了, 很多, 照片, 。]","[張三, 在, 台北, 101, 前面, 拍, 了, 很多, 照片, 。]","(張三, 台北101)","(張三, 台北)","(張三, 台北, 101)"
1,李四昨天在台中火車站迷路了。,"[李四, 昨天, 在, 台中, 火車站, 迷路, 了, 。]","[李四, 昨天, 在, 台中, 火車站, 迷路, 了, 。]","(李四, 昨天, 台中火車站)","(李四, 台中火車站)","(李四, 昨天, 台中火車站)"
2,王五參加了鴻海公司的年度大會。,"[王五, 參加, 了, 鴻海, 公司, 的, 年度, 大會, 。]","[王五, 參加, 了, 鴻海公司, 的, 年度, 大會, 。]","(王五, 鴻海公司)","(王五, 鴻海公司)","(王五, 鴻海公司)"
3,華為手機在全球市場上的銷量持續增長。,"[華為, 手機, 在, 全球, 市場, 上, 的, 銷量, 持續, 增長, 。]","[華為, 手機, 在, 全球, 市場, 上, 的, 銷量, 持續, 增長, 。]","(華為,)",(),"(華為,)"
4,張三開了一間叫做「香格里拉」的餐廳。,"[張三, 開, 了, 一, 間, 叫做, 「, 香格里拉, 」, 的, 餐廳, 。]","[張三, 開, 了, 一, 間, 叫做, 「, 香格里拉, 」, 的, 餐廳, 。]","(張三,)","(張三,)","(張三,)"
5,小明帶著他的iPhone去了華山藝文中心。,"[小明, 帶, 著, 他, 的, iPhone, 去, 了, 華山, 藝文, 中心, 。]","[小明, 帶, 著, 他, 的, iPhone, 去, 了, 華山藝文中心, 。]","(iPhone, 華山藝文中心)","(小明, 華山藝文中心)","(小明, 華山藝文中心)"
6,你知道Apple的總部在哪裡嗎？,"[你, 知道, Apple, 的, 總部, 在, 哪裡, 嗎, ？]","[你, 知道, Apple, 的, 總部, 在, 哪裡, 嗎, ？]","(Apple,)",(),"(Apple,)"
7,昨天在星巴克遇見了老朋友林小明。,"[昨天, 在, 星巴克, 遇見, 了, 老朋友, 林小明, 。]","[昨天, 在, 星巴克, 遇見, 了, 老朋友, 林小明, 。]","(昨天, 星巴克, 林小明)","(星巴克, 林小明)","(昨天, 星巴克, 林小明)"
8,上海是中國的經濟中心。,"[上海, 是, 中國, 的, 經濟, 中心, 。]","[上海, 是, 中國, 的, 經濟, 中心, 。]","(上海, 中國)","(上海, 中國)","(上海, 中國)"
9,Google正在開發一個新的AI模型。,"[Google, 正在, 開發, 一, 個, 新, 的, AI, 模型, 。]","[Google, 正在, 開發, 一個, 新, 的, AI, 模型, 。]","(Google,)",(),"(Google,)"
10,馬雲創辦的阿里巴巴是中國最大的電商平台之一。,"[馬雲, 創辦, 的, 阿里巴巴, 是, 中國, 最, 大, 的, 電商, 平台, 之, 一...","[馬雲, 創辦, 的, 阿里巴巴, 是, 中國, 最大, 的, 電商, 平台, 之一, 。]","(馬雲, 阿里巴巴, 中國, 一)","(馬雲, 中國)","(馬雲, 阿里巴巴, 中國)"
11,珠穆朗瑪峰是世界最高的山。,"[珠穆朗瑪峰, 是, 世界, 最, 高, 的, 山, 。]","[珠穆朗瑪峰, 是, 世界, 最高, 的, 山, 。]","(珠穆朗瑪峰,)","(珠穆朗瑪峰,)","(珠穆朗瑪峰,)"
12,高雄的六合夜市是美食愛好者的天堂。,"[高雄, 的, 六合, 夜市, 是, 美食, 愛好, 者, 的, 天堂, 。]","[高雄, 的, 六合, 夜市, 是, 美食, 愛好者, 的, 天堂, 。]","(高雄, 六合夜市)","(高雄,)","(高雄, 六合夜市)"
13,臺灣大學的學生來參加這次比賽。,"[臺灣, 大學, 的, 學生, 來, 參加, 這, 次, 比賽, 。]","[臺灣, 大學, 的, 學生, 來, 參加, 這次, 比賽, 。]","(臺灣, 大學)","(臺灣大學,)","(臺灣大學,)"
14,蘋果電腦的發明改變了整個科技產業。,"[蘋果, 電腦, 的, 發明, 改變, 了, 整, 個, 科技, 產業, 。]","[蘋果, 電腦, 的, 發明, 改變, 了, 整個, 科技, 產業, 。]","(蘋果,)",(),"(蘋果,)"
15,中國移動的用戶數量每年都在增加。,"[中國, 移動, 的, 用戶, 數量, 每, 年, 都, 在, 增加, 。]","[中國, 移動, 的, 用戶, 數量, 每年, 都, 在, 增加, 。]","(中國,)","(中國,)","(中國,)"
16,香港的金融市場非常活躍。,"[香港, 的, 金融, 市場, 非常, 活躍, 。]","[香港, 的, 金融市場, 非常, 活躍, 。]","(香港,)","(香港,)","(香港,)"
17,IBM推出了一款全新的量子計算機。,"[IBM, 推出, 了, 一, 款, 全新, 的, 量子, 計算機, 。]","[IBM, 推出, 了, 一, 款, 全新, 的, 量子計算機, 。]","(IBM, 一)",(),"(IBM,)"
18,Microsoft的Windows系統是全球最常用的操作系統之一。,"[Microsoft, 的, Windows, 系統, 是, 全球, 最, 常用, 的, 操...","[Microsoft, 的, Windows, 系統, 是, 全球, 最, 常用, 的, 操...","(Microsoft, Windows系統)",(),"(Microsoft,)"
19,劉德華出演了很多經典的電影。,"[劉德華, 出演, 了, 很多, 經典, 的, 電影, 。]","[劉德華, 出演, 了, 很多, 經典, 的, 電影, 。]","(劉德華,)","(劉德華,)","(劉德華,)"
20,台灣的玉山是當地最高的山峰。,"[台灣, 的, 玉山, 是, 當地, 最, 高, 的, 山峰, 。]","[台灣, 的, 玉山, 是, 當地, 最高, 的, 山峰, 。]","(台灣, 玉山)","(台灣, 玉山)","(台灣, 玉山)"
21,世界衛生組織在日內瓦總部召開會議。,"[世界, 衛生, 組織, 在, 日內瓦, 總部, 召開, 會議, 。]","[世界衛生組織, 在, 日內瓦, 總部, 召開, 會議, 。]","(世界衛生組織, 日內瓦)","(世界衛生組織, 日內瓦)","(世界衛生組織, 日內瓦總部)"
22,任天堂的Switch遊戲機在全球大受歡迎。,"[任天堂, 的, Switch, 遊戲機, 在, 全球, 大, 受, 歡迎, 。]","[任天堂, 的, Switch, 遊戲, 機, 在, 全球, 大, 受, 歡迎, 。]","(任天堂,)","(任天堂,)","(任天堂,)"
23,中央電視台播放了關於新冠疫情的最新報導。,"[中央, 電視台, 播放, 了, 關於, 新冠, 疫情, 的, 最新, 報導, 。]","[中央電視台, 播放, 了, 關於, 新冠, 疫情, 的, 最新, 報導, 。]","(中央電視台,)","(中央電視台,)","(中央電視台,)"
24,奧林匹克運動會將在東京舉行。,"[奧林匹克, 運動會, 將, 在, 東京, 舉行, 。]","[奧林匹克, 運動會, 將, 在, 東京, 舉行, 。]","(奧林匹克運動會, 東京)","(東京,)","(東京,)"
25,特斯拉的自動駕駛技術引發了廣泛關注。,"[特斯拉, 的, 自動, 駕駛, 技術, 引發, 了, 廣泛, 關注, 。]","[特斯拉, 的, 自動, 駕駛, 技術, 引發, 了, 廣泛, 關注, 。]","(特斯拉,)","(特斯拉,)","(特斯拉,)"
26,小紅書是一個非常受歡迎的社交平台。,"[小紅書, 是, 一, 個, 非常, 受, 歡迎, 的, 社交, 平台, 。]","[小紅書, 是, 一個, 非常, 受, 歡迎, 的, 社交, 平台, 。]","(一,)",(),()
27,Facebook的隱私政策再次引發爭議。,"[Facebook, 的, 隱私, 政策, 再次, 引發, 爭議, 。]","[Facebook, 的, 隱私, 政策, 再次, 引發, 爭議, 。]","(Facebook,)",(),"(再次,)"
28,日本的富士山每年都吸引大量遊客。,"[日本, 的, 富士山, 每, 年, 都, 吸引, 大量, 遊客, 。]","[日本, 的, 富士山, 每年, 都, 吸引, 大量, 遊客, 。]","(日本, 富士山)","(日本, 富士山)","(日本, 富士山)"
29,李小龍的武術精神影響了全世界。,"[李小龍, 的, 武術, 精神, 影響, 了, 全世界, 。]","[李小龍, 的, 武術, 精神, 影響, 了, 全世界, 。]","(李小龍,)","(李小龍,)","(李小龍,)"

### spaCy

In [ ]:
src_sent = []
tok_res = []
ent_res = []


for source_sentence in test_sentence["sentences"]:
  src_sent.append(source_sentence)

  doc = nlp(source_sentence)
  tok = list(list(token.text for token in doc))

  tok_res.append(tok)

  ent_r = tuple(list(str(ent) for ent in doc.ents))
  ent_res.append(ent_r)

In [ ]:
import pandas as pd

df = pd.DataFrame(list(zip(src_sent, tok_res, ent_res)),
               columns =['原句', '分詞' , '實體'])

df.head(30)

,原句,分詞,實體
0,張三在台北101前面拍了很多照片。,"[張三, 在, 台北, 101, 前面, 拍, 了, 很多, 照片, 。]","(張三, 台北101)"
1,李四昨天在台中火車站迷路了。,"[李四, 昨天, 在, 台中, 火車站, 迷路, 了, 。]","(李四, 昨天, 台中火車站)"
2,王五參加了鴻海公司的年度大會。,"[王五參, 加, 了, 鴻海, 公司, 的, 年度, 大會, 。]","(王五參, 鴻海公司)"
3,華為手機在全球市場上的銷量持續增長。,"[華為, 手機, 在, 全球, 市場, 上, 的, 銷量, 持續, 增長, 。]",()
4,張三開了一間叫做「香格里拉」的餐廳。,"[張, 三, 開, 了, 一, 間, 叫做, 「, 香格里拉, 」, 的, 餐廳, 。]","(張三, 一, 香格里拉)"
5,小明帶著他的iPhone去了華山藝文中心。,"[小明, 帶著, 他, 的, iPhone, 去, 了, 華山, 藝文, 中心, 。]","(華山藝文中心,)"
6,你知道Apple的總部在哪裡嗎？,"[你, 知道, Apple, 的, 總部, 在, 哪, 裡嗎, ？]","(Apple,)"
7,昨天在星巴克遇見了老朋友林小明。,"[昨天, 在, 星巴克, 遇見, 了, 老朋友, 林小明, 。]","(星巴克, 林小明)"
8,上海是中國的經濟中心。,"[上海, 是, 中國, 的, 經濟, 中心, 。]","(上海,)"
9,Google正在開發一個新的AI模型。,"[Google, 正在, 開發, 一, 個, 新, 的, AI, 模型, 。]","(Google,)"
10,馬雲創辦的阿里巴巴是中國最大的電商平台之一。,"[馬雲, 創辦, 的, 阿里巴巴, 是, 中國, 最, 大, 的, 電商, 平台, 之一, 。]","(馬雲, 阿里巴巴)"
11,珠穆朗瑪峰是世界最高的山。,"[珠穆朗, 瑪峰, 是, 世界, 最, 高, 的, 山, 。]","(珠穆朗瑪峰,)"
12,高雄的六合夜市是美食愛好者的天堂。,"[高雄, 的, 六合夜市, 是, 美食, 愛好者, 的, 天堂, 。]","(高雄的六合夜市,)"
13,臺灣大學的學生來參加這次比賽。,"[臺灣, 大學, 的, 學生, 來參, 加, 這次, 比賽, 。]","(臺灣大學,)"
14,蘋果電腦的發明改變了整個科技產業。,"[蘋果, 電腦, 的, 發明, 改變, 了, 整個, 科技, 產業, 。]",()
15,中國移動的用戶數量每年都在增加。,"[中國, 移動, 的, 用戶, 數量, 每年, 都, 在, 增加, 。]",()
16,香港的金融市場非常活躍。,"[香港, 的, 金融, 市場, 非常, 活躍, 。]","(香港,)"
17,IBM推出了一款全新的量子計算機。,"[IBM, 推出, 了, 一, 款, 全新, 的, 量子, 計, 算機, 。]","(IBM,)"
18,Microsoft的Windows系統是全球最常用的操作系統之一。,"[Microsoft, 的, Windows, 系統, 是, 全球, 最, 常用, 的, 操...","(Microsoft,)"
19,劉德華出演了很多經典的電影。,"[劉德華, 出演, 了, 很多, 經典, 的, 電影, 。]","(劉德華,)"
20,台灣的玉山是當地最高的山峰。,"[台灣, 的, 玉山, 是, 當地, 最, 高, 的, 山峰, 。]","(台灣, 玉山)"
21,世界衛生組織在日內瓦總部召開會議。,"[世界, 衛生, 組織, 在, 日內, 瓦總部, 召開, 會議, 。]","(世界衛生組織, 日內瓦總部)"
22,任天堂的Switch遊戲機在全球大受歡迎。,"[任天堂, 的, Switch, 遊, 戲機, 在, 全球, 大, 受, 歡迎, 。]","(任天堂,)"
23,中央電視台播放了關於新冠疫情的最新報導。,"[中央, 電視台, 播放, 了, 關於, 新冠, 疫情, 的, 最新, 報導, 。]","(中央電視台,)"
24,奧林匹克運動會將在東京舉行。,"[奧林匹克, 運動, 會將, 在, 東京, 舉行, 。]","(奧林匹克運動會將, 東京)"
25,特斯拉的自動駕駛技術引發了廣泛關注。,"[特斯拉, 的, 自動, 駕駛, 技術, 引發, 了, 廣泛, 關注, 。]","(特斯拉,)"
26,小紅書是一個非常受歡迎的社交平台。,"[小, 紅書, 是, 一, 個, 非常, 受, 歡迎, 的, 社交, 平台, 。]",()
27,Facebook的隱私政策再次引發爭議。,"[Facebook, 的, 隱私, 政策, 再次, 引發, 爭議, 。]","(Facebook,)"
28,日本的富士山每年都吸引大量遊客。,"[日本, 的, 富士山, 每年, 都, 吸引, 大量, 遊客, 。]","(日本, 富士山)"
29,李小龍的武術精神影響了全世界。,"[李小龍, 的, 武術, 精神, 影響, 了, 全世界, 。]","(李小龍,)"