In [2]:
!pip install -qU pip setuptools wheel
!pip install -qU spacy
!python -m spacy download zh_core_web_sm
!python -m spacy download zh_core_web_md
!python -m spacy download zh_core_web_lg
!python -m spacy download zh_core_web_trf

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
Collecting zh-core-web-sm==3.7.0
  Downloading https://github.com/explosion/spacy-models/releases/download/zh_core_web_sm-3.7.0/zh_core_web_sm-3.7.0-py3-none-any.whl (48.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 MB 54.3 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.8.0,>=3.7.0 in /usr/local/lib/python3.10/dist-packages (from zh-core-web-sm==3.7.0) (3.7.6)
Collecting spacy-pkuseg<0.1.0,>=0.0.27 (from zh-core-web-sm==3.7.0)
  Downloading spacy_pkuseg-0.0.33-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (0.12.5)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (4.66.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2.9.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (3.1.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (75.1.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (24.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (3.4.0)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (1.26.4)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.10/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (1.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2.23.4)
Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2024.8.30)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (13.8.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (0.19.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (7.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2.1.5)
Requirement already satisfied: marisa-trie>=0.7.7 in /usr/local/lib/python3.10/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (1.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (2.18.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.10/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (1.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-sm==3.7.0) (0.1.2)
Downloading spacy_pkuseg-0.0.33-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 74.1 MB/s eta 0:00:00
Installing collected packages: spacy-pkuseg, zh-core-web-sm
Successfully installed spacy-pkuseg-0.0.33 zh-core-web-sm-3.7.0
✔ Download and installation successful
You can now load the package via spacy.load('zh_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
Collecting zh-core-web-md==3.7.0
  Downloading https://github.com/explosion/spacy-models/releases/download/zh_core_web_md-3.7.0/zh_core_web_md-3.7.0-py3-none-any.whl (78.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.0/78.0 MB 49.9 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.8.0,>=3.7.0 in /usr/local/lib/python3.10/dist-packages (from zh-core-web-md==3.7.0) (3.7.6)
Requirement already satisfied: spacy-pkuseg<0.1.0,>=0.0.27 in /usr/local/lib/python3.10/dist-packages (from zh-core-web-md==3.7.0) (0.0.33)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (0.12.5)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (4.66.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2.9.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (3.1.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (75.1.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (24.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (3.4.0)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (1.26.4)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.10/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (1.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2.23.4)
Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2024.8.30)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (13.8.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (0.19.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (7.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2.1.5)
Requirement already satisfied: marisa-trie>=0.7.7 in /usr/local/lib/python3.10/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (1.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (2.18.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.10/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (1.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.0->zh-core-web-md==3.7.0) (0.1.2)
Installing collected packages: zh-core-web-md
Successfully installed zh-core-web-md-3.7.0
✔ Download and installation successful
You can now load the package via spacy.load('zh_core_web_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
Collecting zh-core-web-lg==3.7.0
  Downloading https://github.com/explosion/spacy-models/releases/download/zh_core_web_lg-3.7.0/zh_core_web_lg-3.7.0-py3-none-any.whl (603.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 603.0/603.0 MB 41.1 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.8.0,>=3.7.0 in /usr/local/lib/python3.10/dist-packages (from zh-core-web-lg==3.7.0) (3.7.6)
Requirement already satisfied: spacy-pkuseg<0.1.0,>=0.0.27 in /usr/local/lib/python3.10/dist-packages (from zh-core-web-lg==3.7.0) (0.0.33)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (0.12.5)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (4.66.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (2.9.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (3.1.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (75.1.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (24.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (3.4.0)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (1.26.4)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.10/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (1.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.0->zh-core-web-lg==3.7.0) (2.23.4)

In [17]:
!pip install -q googletrans==4.0.0-rc1

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 50.9 MB/s eta 0:00:00
  Building wheel for googletrans (setup.py) ... done

# 30 個繁體中文句子

* Generated by Chatgpt-4o.
* Ref with [a messy dialogue](https://chatgpt.com/share/d5b671c8-432d-4465-a8bc-5255c73b3ee6).

In [4]:
test_sentence = {
  "sentences": [
    "張三在台北101前面拍了很多照片。",
    "李四昨天在台中火車站迷路了。",
    "王五參加了鴻海公司的年度大會。",
    "華為手機在全球市場上的銷量持續增長。",
    "張三開了一間叫做「香格里拉」的餐廳。",
    "小明帶著他的iPhone去了華山藝文中心。",
    "你知道Apple的總部在哪裡嗎？",
    "昨天在星巴克遇見了老朋友林小明。",
    "上海是中國的經濟中心。",
    "Google正在開發一個新的AI模型。",
    "馬雲創辦的阿里巴巴是中國最大的電商平台之一。",
    "珠穆朗瑪峰是世界最高的山。",
    "高雄的六合夜市是美食愛好者的天堂。",
    "臺灣大學的學生來參加這次比賽。",
    "蘋果電腦的發明改變了整個科技產業。",
    "中國移動的用戶數量每年都在增加。",
    "香港的金融市場非常活躍。",
    "IBM推出了一款全新的量子計算機。",
    "Microsoft的Windows系統是全球最常用的操作系統之一。",
    "劉德華出演了很多經典的電影。",
    "台灣的玉山是當地最高的山峰。",
    "世界衛生組織在日內瓦總部召開會議。",
    "任天堂的Switch遊戲機在全球大受歡迎。",
    "中央電視台播放了關於新冠疫情的最新報導。",
    "奧林匹克運動會將在東京舉行。",
    "特斯拉的自動駕駛技術引發了廣泛關注。",
    "小紅書是一個非常受歡迎的社交平台。",
    "Facebook的隱私政策再次引發爭議。",
    "日本的富士山每年都吸引大量遊客。",
    "李小龍的武術精神影響了全世界。"
  ]
}

In [4]:
from googletrans import Translator
import spacy
from spacy.tokens import Span

nlp = spacy.load("zh_core_web_trf")

src_sent = []
trans_res = []
src_ents = []
# 翻譯器
translator = Translator()

for source_sentence in test_sentence["sentences"]:
  src_sent.append(source_sentence)
  current_translation = translator.translate(source_sentence, src = "zh-TW", dest='en')
  trans_res.append(current_translation.text)

  doc = nlp(source_sentence)
  ent = tuple(list(str(ent) for ent in doc.ents))
  src_ents.append(ent)

/usr/local/lib/python3.10/dist-packages/thinc/shims/pytorch.py:253: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(filelike, map_location=device))
/usr/local/lib/python3.10/dist-packages/thinc/shims/pytorch.py:114: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(self._mixed_precision):

In [5]:
import pandas as pd

df = pd.DataFrame(list(zip(src_sent, src_ents, trans_res)),
               columns =['原句', '原句的專有名詞','翻譯'])

df.head(30)

,原句,原句的專有名詞,翻譯
0,張三在台北101前面拍了很多照片。,"(張三, 台北101)",Zhang San took a lot of photos in front of Tai...
1,李四昨天在台中火車站迷路了。,"(李四, 昨天, 台中火車站)",Li Si was lost at Taichung Railway Station yes...
2,王五參加了鴻海公司的年度大會。,"(王五參, 鴻海公司)",Wang Wu participated in the annual conference ...
3,華為手機在全球市場上的銷量持續增長。,(),The sales of Huawei mobile phones in the globa...
4,張三開了一間叫做「香格里拉」的餐廳。,"(張三, 一, 香格里拉)","Zhang San opened a restaurant called ""Shangri ..."
5,小明帶著他的iPhone去了華山藝文中心。,"(華山藝文中心,)",Xiaoming took his iPhone to Huashan Art and Cu...
6,你知道Apple的總部在哪裡嗎？,"(Apple,)",Do you know where the headquarters of Apple is?
7,昨天在星巴克遇見了老朋友林小明。,"(星巴克, 林小明)",I met an old friend Lin Xiaoming in Starbucks ...
8,上海是中國的經濟中心。,"(上海,)",Shanghai is the economic center of China.
9,Google正在開發一個新的AI模型。,"(Google,)",Google is developing a new AI model.
10,馬雲創辦的阿里巴巴是中國最大的電商平台之一。,"(馬雲, 阿里巴巴)",Alibaba founded by Jack Ma is one of China's l...
11,珠穆朗瑪峰是世界最高的山。,"(珠穆朗瑪峰,)",Mount Everest is the tallest mountain in the w...
12,高雄的六合夜市是美食愛好者的天堂。,"(高雄的六合夜市,)",Kaohsiung's Liuhe Night Market is a paradise f...
13,臺灣大學的學生來參加這次比賽。,"(臺灣大學,)",Students from Taiwan University come to partic...
14,蘋果電腦的發明改變了整個科技產業。,(),The invention of Apple Computer has changed th...
15,中國移動的用戶數量每年都在增加。,(),The number of Chinese mobile users is increasi...
16,香港的金融市場非常活躍。,"(香港,)",Hong Kong's financial market is very active.
17,IBM推出了一款全新的量子計算機。,"(IBM,)",IBM launched a new quantum computer.
18,Microsoft的Windows系統是全球最常用的操作系統之一。,"(Microsoft,)",Microsoft's Windows system is one of the most ...
19,劉德華出演了很多經典的電影。,"(劉德華,)",Andy Lau has appeared in many classic movies.
20,台灣的玉山是當地最高的山峰。,"(台灣, 玉山)",Yushan in Taiwan is the tallest mountain peak.
21,世界衛生組織在日內瓦總部召開會議。,"(世界衛生組織, 日內瓦總部)",The World Health Organization held a meeting a...
22,任天堂的Switch遊戲機在全球大受歡迎。,"(任天堂,)",Nintendo's Switch game console is very popular...
23,中央電視台播放了關於新冠疫情的最新報導。,"(中央電視台,)",CCTV played the latest report on the new crown...
24,奧林匹克運動會將在東京舉行。,"(奧林匹克運動會將, 東京)",The Olympic Games will be held in Tokyo.
25,特斯拉的自動駕駛技術引發了廣泛關注。,"(特斯拉,)",Tesla's autonomous driving technology has attr...
26,小紅書是一個非常受歡迎的社交平台。,(),Xiaohongshu is a very popular social platform.
27,Facebook的隱私政策再次引發爭議。,"(Facebook,)",Facebook's privacy policy once again caused co...
28,日本的富士山每年都吸引大量遊客。,"(日本, 富士山)",Mount Fuji in Japan attracts a large number of...
29,李小龍的武術精神影響了全世界。,"(李小龍,)",Bruce Lee's martial arts spirit has affected t...

In [6]:
type(src_ents[24])

tuple

## 修正

##移除錯誤的實體

In [7]:
#移除錯誤的實體
remove = [("",), ("昨天",), ("王五參",), ("",), ("一",), ("",), ("",), ("",), ("",), ("",), ("",), ("",), ("",), ("",), ("",), ("",), ("",), ("",), ("",), ("",), ("",), ("",), ("",), ("",), ("奧林匹克運動會將",), ("",), ("",), ("",), ("",), ("",),]

##加入正確的實體
addition = [("",), ("",), ("王五",), ("華為",), ("",), ("小明", "iPhone",), ("",), ("",), ("中國",), ("AI",), ("中國",), ("",), ("",), ("",), ("蘋果",), ("中國移動",), ("",), ("",), ("Windows",), ("",), ("",), ("",), ("Switch",), ("新冠疫情",), ("奧林匹克運動會",), ("",), ("小紅書",), ("隱私政策",), ("",), ("",),]

In [8]:
print(len(remove))
print(len(addition))

30
30

In [9]:
import pandas as pd

df = pd.DataFrame(list(zip(src_sent, src_ents, trans_res, remove, addition)),
               columns =['原句', '原句的專有名詞','翻譯', '移除', '需加入'])

df.head(30)

,原句,原句的專有名詞,翻譯,移除,需加入
0,張三在台北101前面拍了很多照片。,"(張三, 台北101)",Zhang San took a lot of photos in front of Tai...,"(,)","(,)"
1,李四昨天在台中火車站迷路了。,"(李四, 昨天, 台中火車站)",Li Si was lost at Taichung Railway Station yes...,"(昨天,)","(,)"
2,王五參加了鴻海公司的年度大會。,"(王五參, 鴻海公司)",Wang Wu participated in the annual conference ...,"(王五參,)","(王五,)"
3,華為手機在全球市場上的銷量持續增長。,(),The sales of Huawei mobile phones in the globa...,"(,)","(華為,)"
4,張三開了一間叫做「香格里拉」的餐廳。,"(張三, 一, 香格里拉)","Zhang San opened a restaurant called ""Shangri ...","(一,)","(,)"
5,小明帶著他的iPhone去了華山藝文中心。,"(華山藝文中心,)",Xiaoming took his iPhone to Huashan Art and Cu...,"(,)","(小明, iPhone)"
6,你知道Apple的總部在哪裡嗎？,"(Apple,)",Do you know where the headquarters of Apple is?,"(,)","(,)"
7,昨天在星巴克遇見了老朋友林小明。,"(星巴克, 林小明)",I met an old friend Lin Xiaoming in Starbucks ...,"(,)","(,)"
8,上海是中國的經濟中心。,"(上海,)",Shanghai is the economic center of China.,"(,)","(中國,)"
9,Google正在開發一個新的AI模型。,"(Google,)",Google is developing a new AI model.,"(,)","(AI,)"
10,馬雲創辦的阿里巴巴是中國最大的電商平台之一。,"(馬雲, 阿里巴巴)",Alibaba founded by Jack Ma is one of China's l...,"(,)","(中國,)"
11,珠穆朗瑪峰是世界最高的山。,"(珠穆朗瑪峰,)",Mount Everest is the tallest mountain in the w...,"(,)","(,)"
12,高雄的六合夜市是美食愛好者的天堂。,"(高雄的六合夜市,)",Kaohsiung's Liuhe Night Market is a paradise f...,"(,)","(,)"
13,臺灣大學的學生來參加這次比賽。,"(臺灣大學,)",Students from Taiwan University come to partic...,"(,)","(,)"
14,蘋果電腦的發明改變了整個科技產業。,(),The invention of Apple Computer has changed th...,"(,)","(蘋果,)"
15,中國移動的用戶數量每年都在增加。,(),The number of Chinese mobile users is increasi...,"(,)","(中國移動,)"
16,香港的金融市場非常活躍。,"(香港,)",Hong Kong's financial market is very active.,"(,)","(,)"
17,IBM推出了一款全新的量子計算機。,"(IBM,)",IBM launched a new quantum computer.,"(,)","(,)"
18,Microsoft的Windows系統是全球最常用的操作系統之一。,"(Microsoft,)",Microsoft's Windows system is one of the most ...,"(,)","(Windows,)"
19,劉德華出演了很多經典的電影。,"(劉德華,)",Andy Lau has appeared in many classic movies.,"(,)","(,)"
20,台灣的玉山是當地最高的山峰。,"(台灣, 玉山)",Yushan in Taiwan is the tallest mountain peak.,"(,)","(,)"
21,世界衛生組織在日內瓦總部召開會議。,"(世界衛生組織, 日內瓦總部)",The World Health Organization held a meeting a...,"(,)","(,)"
22,任天堂的Switch遊戲機在全球大受歡迎。,"(任天堂,)",Nintendo's Switch game console is very popular...,"(,)","(Switch,)"
23,中央電視台播放了關於新冠疫情的最新報導。,"(中央電視台,)",CCTV played the latest report on the new crown...,"(,)","(新冠疫情,)"
24,奧林匹克運動會將在東京舉行。,"(奧林匹克運動會將, 東京)",The Olympic Games will be held in Tokyo.,"(奧林匹克運動會將,)","(奧林匹克運動會,)"
25,特斯拉的自動駕駛技術引發了廣泛關注。,"(特斯拉,)",Tesla's autonomous driving technology has attr...,"(,)","(,)"
26,小紅書是一個非常受歡迎的社交平台。,(),Xiaohongshu is a very popular social platform.,"(,)","(小紅書,)"
27,Facebook的隱私政策再次引發爭議。,"(Facebook,)",Facebook's privacy policy once again caused co...,"(,)","(隱私政策,)"
28,日本的富士山每年都吸引大量遊客。,"(日本, 富士山)",Mount Fuji in Japan attracts a large number of...,"(,)","(,)"
29,李小龍的武術精神影響了全世界。,"(李小龍,)",Bruce Lee's martial arts spirit has affected t...,"(,)","(,)"

In [10]:
update_ents = []

for idx in range(len(src_ents)):

  item = list(src_ents[idx])
  rm = list(remove[idx])
  ad = list(addition[idx])

  if len(rm) == 1 and rm[0]== '':
    pass
  else:
    for ii in rm:
      item.remove(ii)

  if len(ad) == 1 and ad[0]== '':
    pass
  else:
    for ii in ad:
      item.append(ii)

  update_ents.append(tuple(item))

print(update_ents)

[('張三', '台北101'), ('李四', '台中火車站'), ('鴻海公司', '王五'), ('華為',), ('張三', '香格里拉'), ('華山藝文中心', '小明', 'iPhone'), ('Apple',), ('星巴克', '林小明'), ('上海', '中國'), ('Google', 'AI'), ('馬雲', '阿里巴巴', '中國'), ('珠穆朗瑪峰',), ('高雄的六合夜市',), ('臺灣大學',), ('蘋果',), ('中國移動',), ('香港',), ('IBM',), ('Microsoft', 'Windows'), ('劉德華',), ('台灣', '玉山'), ('世界衛生組織', '日內瓦總部'), ('任天堂', 'Switch'), ('中央電視台', '新冠疫情'), ('東京', '奧林匹克運動會'), ('特斯拉',), ('小紅書',), ('Facebook', '隱私政策'), ('日本', '富士山'), ('李小龍',)]

In [11]:
import pandas as pd

df = pd.DataFrame(list(zip(src_sent, src_ents, trans_res, remove, addition, update_ents)),
               columns =['原句', '原句的專有名詞(vanilla)','翻譯', '移除', '需加入', '原句的專有名詞(revised)'])

df.head(30)

,原句,原句的專有名詞(vanilla),翻譯,移除,需加入,原句的專有名詞(revised)
0,張三在台北101前面拍了很多照片。,"(張三, 台北101)",Zhang San took a lot of photos in front of Tai...,"(,)","(,)","(張三, 台北101)"
1,李四昨天在台中火車站迷路了。,"(李四, 昨天, 台中火車站)",Li Si was lost at Taichung Railway Station yes...,"(昨天,)","(,)","(李四, 台中火車站)"
2,王五參加了鴻海公司的年度大會。,"(王五參, 鴻海公司)",Wang Wu participated in the annual conference ...,"(王五參,)","(王五,)","(鴻海公司, 王五)"
3,華為手機在全球市場上的銷量持續增長。,(),The sales of Huawei mobile phones in the globa...,"(,)","(華為,)","(華為,)"
4,張三開了一間叫做「香格里拉」的餐廳。,"(張三, 一, 香格里拉)","Zhang San opened a restaurant called ""Shangri ...","(一,)","(,)","(張三, 香格里拉)"
5,小明帶著他的iPhone去了華山藝文中心。,"(華山藝文中心,)",Xiaoming took his iPhone to Huashan Art and Cu...,"(,)","(小明, iPhone)","(華山藝文中心, 小明, iPhone)"
6,你知道Apple的總部在哪裡嗎？,"(Apple,)",Do you know where the headquarters of Apple is?,"(,)","(,)","(Apple,)"
7,昨天在星巴克遇見了老朋友林小明。,"(星巴克, 林小明)",I met an old friend Lin Xiaoming in Starbucks ...,"(,)","(,)","(星巴克, 林小明)"
8,上海是中國的經濟中心。,"(上海,)",Shanghai is the economic center of China.,"(,)","(中國,)","(上海, 中國)"
9,Google正在開發一個新的AI模型。,"(Google,)",Google is developing a new AI model.,"(,)","(AI,)","(Google, AI)"
10,馬雲創辦的阿里巴巴是中國最大的電商平台之一。,"(馬雲, 阿里巴巴)",Alibaba founded by Jack Ma is one of China's l...,"(,)","(中國,)","(馬雲, 阿里巴巴, 中國)"
11,珠穆朗瑪峰是世界最高的山。,"(珠穆朗瑪峰,)",Mount Everest is the tallest mountain in the w...,"(,)","(,)","(珠穆朗瑪峰,)"
12,高雄的六合夜市是美食愛好者的天堂。,"(高雄的六合夜市,)",Kaohsiung's Liuhe Night Market is a paradise f...,"(,)","(,)","(高雄的六合夜市,)"
13,臺灣大學的學生來參加這次比賽。,"(臺灣大學,)",Students from Taiwan University come to partic...,"(,)","(,)","(臺灣大學,)"
14,蘋果電腦的發明改變了整個科技產業。,(),The invention of Apple Computer has changed th...,"(,)","(蘋果,)","(蘋果,)"
15,中國移動的用戶數量每年都在增加。,(),The number of Chinese mobile users is increasi...,"(,)","(中國移動,)","(中國移動,)"
16,香港的金融市場非常活躍。,"(香港,)",Hong Kong's financial market is very active.,"(,)","(,)","(香港,)"
17,IBM推出了一款全新的量子計算機。,"(IBM,)",IBM launched a new quantum computer.,"(,)","(,)","(IBM,)"
18,Microsoft的Windows系統是全球最常用的操作系統之一。,"(Microsoft,)",Microsoft's Windows system is one of the most ...,"(,)","(Windows,)","(Microsoft, Windows)"
19,劉德華出演了很多經典的電影。,"(劉德華,)",Andy Lau has appeared in many classic movies.,"(,)","(,)","(劉德華,)"
20,台灣的玉山是當地最高的山峰。,"(台灣, 玉山)",Yushan in Taiwan is the tallest mountain peak.,"(,)","(,)","(台灣, 玉山)"
21,世界衛生組織在日內瓦總部召開會議。,"(世界衛生組織, 日內瓦總部)",The World Health Organization held a meeting a...,"(,)","(,)","(世界衛生組織, 日內瓦總部)"
22,任天堂的Switch遊戲機在全球大受歡迎。,"(任天堂,)",Nintendo's Switch game console is very popular...,"(,)","(Switch,)","(任天堂, Switch)"
23,中央電視台播放了關於新冠疫情的最新報導。,"(中央電視台,)",CCTV played the latest report on the new crown...,"(,)","(新冠疫情,)","(中央電視台, 新冠疫情)"
24,奧林匹克運動會將在東京舉行。,"(奧林匹克運動會將, 東京)",The Olympic Games will be held in Tokyo.,"(奧林匹克運動會將,)","(奧林匹克運動會,)","(東京, 奧林匹克運動會)"
25,特斯拉的自動駕駛技術引發了廣泛關注。,"(特斯拉,)",Tesla's autonomous driving technology has attr...,"(,)","(,)","(特斯拉,)"
26,小紅書是一個非常受歡迎的社交平台。,(),Xiaohongshu is a very popular social platform.,"(,)","(小紅書,)","(小紅書,)"
27,Facebook的隱私政策再次引發爭議。,"(Facebook,)",Facebook's privacy policy once again caused co...,"(,)","(隱私政策,)","(Facebook, 隱私政策)"
28,日本的富士山每年都吸引大量遊客。,"(日本, 富士山)",Mount Fuji in Japan attracts a large number of...,"(,)","(,)","(日本, 富士山)"
29,李小龍的武術精神影響了全世界。,"(李小龍,)",Bruce Lee's martial arts spirit has affected t...,"(,)","(,)","(李小龍,)"

In [12]:
rule = dict()

for voc in update_ents[27]:
  rule[voc] = [voc]
sentence = src_sent[27]

In [13]:
rule

{'Facebook': ['Facebook'], '隱私政策': ['隱私政策']}

In [14]:
import spacy
from spacy.tokenizer import Tokenizer
from spacy.lang.zh import Chinese
from spacy.symbols import ORTH

# Example sentence
# sentence = "Facebook的隱私政策再次引發爭議。"

# Create a Chinese nlp object
nlp = Chinese()

# Define custom tokenization rules
# rule = {'Facebook': ['Facebook'], '隱私政策': ['隱私政策']}

# Define a custom tokenizer
def custom_tokenizer(nlp):
    # Create the default tokenizer
    tokenizer = Tokenizer(nlp.vocab)

    # Add special cases (e.g., 'Facebook' and '隱私政策' as single tokens)
    for token in rule:
        tokenizer.add_special_case(token, [{ORTH: token}])

    return tokenizer

# Set the custom tokenizer
nlp.tokenizer = custom_tokenizer(nlp)

# Process the sentence
doc = nlp(sentence)

# Print the tokens
for token in doc:
    print(token.text)

Facebook的隱私政策再次引發爭議。

In [10]:
import spacy
from spacy.lang.zh.examples import sentences

nlp = spacy.load("zh_core_web_sm")
doc = nlp("Facebook的隱私政策再次引發爭議。")
print(doc.text)
for token in doc:
    print(token.text, token.pos_, token.dep_)

Facebook的隱私政策再次引發爭議。
Facebook PROPN nmod:assmod
的 PART case
隱私 NOUN compound:nn
政策 NOUN compound:nn
再次 ADV advmod
引發 NOUN compound:nn
爭議 NOUN ROOT
。 PUNCT punct

TypeError: sequence item 0: expected str instance, list found

In [12]:
type(doc)
#spacy.tokens.doc.Doc
"".join([token.text] for token in doc)

spacy.tokens.doc.Doc

In [14]:
"/".join([token.text for token in doc])

'Facebook/的/隱私/政策/再次/引發/爭議/。'

In [ ]:
update_ents

In [5]:
import spacy

nlp = spacy.load("zh_core_web_sm")
ruler = nlp.add_pipe("entity_ruler")
patterns = [{"label": "ORG", "pattern": "Facebook"},
            {"label": "LAW", "pattern": "隱私政策"}]
ruler.add_patterns(patterns)

doc = nlp("Facebook的隱私政策再次引發爭議。")
print([(ent.text, ent.label_) for ent in doc.ents])

[('Facebook', 'ORG'), ('隱私政策', 'LAW')]

In [8]:
#(馬雲, 阿里巴巴, 中國)
# 馬雲創辦的阿里巴巴是中國最大的電商平台之一。

import spacy

# 加載 spaCy 的中文模型
nlp = spacy.load("zh_core_web_sm")

# 添加 entity_ruler 管道
ruler = nlp.add_pipe("entity_ruler", before="ner")
patterns = [{"label": "ORG", "pattern": "Facebook"},
            {"label": "LAW", "pattern": "隱私政策"}]

ruler.add_patterns(patterns)

# 定義文本
doc = nlp("Facebook的隱私政策再次引發爭議。")

# 遍歷 token，將實體作為一個單位，非實體逐詞分割
tokens = []
i = 0
while i < len(doc):
    if doc[i].ent_iob_ == 'B':  # 如果是實體的開始
        entity = []
        # 將整個實體加入 tokens 列表
        while i < len(doc) and doc[i].ent_iob_ != 'O':  # 直到實體結束
            entity.append(doc[i].text)
            i += 1
        tokens.append("".join(entity))  # 合併實體的所有部分
    else:
        tokens.append(doc[i].text)
        i += 1

# 按行打印每個 token 或實體
for token in tokens:
    print(token)

Facebook
的
隱私政策
再次
引發
爭議
。

In [9]:
tokens

['Facebook', '的', '隱私政策', '再次', '引發', '爭議', '。']

In [3]:
# from googletrans import Translator
import spacy
from spacy.tokens import Span

nlp = spacy.load("zh_core_web_trf")
doc = nlp("馬雲創辦的阿里巴巴是中國最大的電商平台之一。")

# for token in doc:
#     print(token.text)

for token in doc:
    print(token.text, token.pos_, token.dep_)

# src_sent = []
# trans_res = []
# src_ents = []
# # 翻譯器
# translator = Translator()

# for source_sentence in test_sentence["sentences"]:
#   src_sent.append(source_sentence)
#   current_translation = translator.translate(source_sentence, src = "zh-TW", dest='en')
#   trans_res.append(current_translation.text)

#   doc = nlp(source_sentence)
#   ent = tuple(list(str(ent) for ent in doc.ents))
#   src_ents.append(ent)

/usr/local/lib/python3.10/dist-packages/thinc/shims/pytorch.py:253: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(filelike, map_location=device))

馬雲 PROPN nsubj
創辦 VERB acl
的 PART mark
阿里巴巴 PROPN nsubj
是 VERB cop
中國 NOUN dep
最 ADV advmod
大 VERB amod
的 PART mark
電商 NOUN compound:nn
平台 NOUN compound:nn
之一 NOUN ROOT
。 PUNCT punct

/usr/local/lib/python3.10/dist-packages/thinc/shims/pytorch.py:114: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(self._mixed_precision):

In [15]:
import spacy

# 加載 spaCy 的中文模型
nlp = spacy.load("zh_core_web_sm")

# 定義一個簡單的文本
doc = nlp("馬雲創辦的阿里巴巴是中國最大的電商平台之一。")

# 遍歷每一個 token 並逐行輸出
for token in doc:
    print(token.text)

馬雲
創辦
的
阿里巴巴
是
中國
最
大
的
電商
平台
之一
。